export const SUGGESTED_JOB_TITLES = [
  'Full Stack Developer',
  'Frontend Engineer',
  'Backend Engineer',
  'DevOps & Cloud Engineer',
  'QA Automation Engineer',
  'UI/UX Designer',
  'Mobile App Developer',
  'Data Engineer',
  'Software Architect',
  'Technical Lead',
  'Engineering Manager',
  'Product Manager',
  'Site Reliability Engineer (SRE)',
  'Cybersecurity Analyst',
  'Machine Learning / AI Engineer',
  'Systems Administrator',
  'Scrum Master / Agile Coach'
];

export const SAMPLE_TASKS_LIBRARY = [
  // Backend & APIs
  {
    id: 'b1',
    category: 'Backend & APIs',
    taskName: 'Implement REST API endpoints & input validation',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 6,
    timeSpent: 6,
    outputDeliverable: 'Tested controllers, routes & validation middleware pushed to repo',
    plannedDetails: 'Build resilient REST endpoints with parameter validation and role checks',
    keywords: ['api', 'rest', 'express', 'endpoint', 'validation', 'controller', 'route']
  },
  {
    id: 'b2',
    category: 'Backend & APIs',
    taskName: 'Database index optimization & MongoDB query tuning',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 3.5,
    outputDeliverable: 'Query latency reduced by 40% on aggregated analytics reports',
    plannedDetails: 'Audit slow query logs and add compound indexes for multi-week lookups',
    keywords: ['database', 'mongodb', 'index', 'query', 'performance', 'latency', 'tuning']
  },
  {
    id: 'b3',
    category: 'Backend & APIs',
    taskName: 'Authentication token handling & session security',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 5,
    outputDeliverable: 'JWT expiration edge cases handled and timing attacks mitigated',
    plannedDetails: 'Implement secure bcrypt comparison timing and token verification gates',
    keywords: ['auth', 'jwt', 'security', 'token', 'bcrypt', 'login', 'session']
  },
  {
    id: 'b4',
    category: 'Backend & APIs',
    taskName: 'Redis caching layer implementation for report endpoints',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 4.5,
    outputDeliverable: 'In-memory Redis cache with cache invalidation on report update',
    plannedDetails: 'Set up Redis cache for heavy aggregated team progress queries',
    keywords: ['redis', 'cache', 'caching', 'performance', 'backend', 'speed']
  },
  {
    id: 'b5',
    category: 'Backend & APIs',
    taskName: 'Asynchronous background worker & task queue implementation',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 90,
    status: 'In Progress',
    plannedTime: 6,
    timeSpent: 5,
    outputDeliverable: 'BullMQ job processor configured with retry and failure alert hooks',
    plannedDetails: 'Offload email digest dispatching and heavy report PDF compiles to worker queue',
    keywords: ['queue', 'worker', 'bullmq', 'async', 'background', 'email', 'jobs']
  },
  {
    id: 'b6',
    category: 'Backend & APIs',
    taskName: 'API rate limiting and DDoS defense middleware',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Sliding window rate limiter configured per IP and authenticated API key',
    plannedDetails: 'Protect auth and export endpoints from brute-force and rapid spam requests',
    keywords: ['rate limit', 'security', 'ddos', 'middleware', 'protection', 'throttling']
  },
  {
    id: 'b7',
    category: 'Backend & APIs',
    taskName: 'Webhook delivery service with retry and signature verification',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: 'HMAC-SHA256 signature verification and exponential backoff retry system',
    plannedDetails: 'Allow external project tracking tools (Jira/GitHub) to sync with status events',
    keywords: ['webhook', 'integration', 'hmac', 'signature', 'events', 'sync']
  },

  // Frontend & UI
  {
    id: 'f1',
    category: 'Frontend & UI',
    taskName: 'Build responsive UI components & interactive state handling',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 6,
    timeSpent: 5.5,
    outputDeliverable: 'Responsive layouts tested across mobile (425px) and desktop viewports',
    plannedDetails: 'Refactor drawer and modals with accessible focus management and smooth transitions',
    keywords: ['ui', 'frontend', 'components', 'responsive', 'mobile', 'css', 'tailwind']
  },
  {
    id: 'f2',
    category: 'Frontend & UI',
    taskName: 'Client-side form validation & error state feedback',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Clear validation banners and inline warning badges added',
    plannedDetails: 'Add comprehensive field-level warnings for required dates and submission metrics',
    keywords: ['validation', 'form', 'errors', 'feedback', 'inputs', 'alert']
  },
  {
    id: 'f3',
    category: 'Frontend & UI',
    taskName: 'Data dashboard charts integration & responsive metrics cards',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 6,
    outputDeliverable: 'Recharts visualization for workload and completion trends',
    plannedDetails: 'Integrate team completion curves and time-spent breakdown charts',
    keywords: ['charts', 'dashboard', 'recharts', 'metrics', 'analytics', 'visualization']
  },
  {
    id: 'f4',
    category: 'Frontend & UI',
    taskName: 'Dark mode & theme switcher implementation',
    priority: 'Low',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 3.5,
    outputDeliverable: 'Persistent dark mode theme with CSS variables and Tailwind dark classes',
    plannedDetails: 'Enable smooth theme toggle with system preference auto-detection',
    keywords: ['dark mode', 'theme', 'ui', 'tailwind', 'styling', 'toggle']
  },
  {
    id: 'f5',
    category: 'Frontend & UI',
    taskName: 'Frontend bundle size optimization & code splitting',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: 'Vite chunk splitting reduced initial JS bundle footprint by 45%',
    plannedDetails: 'Implement lazy loading on report history and heavy chart view components',
    keywords: ['performance', 'bundle', 'vite', 'lazy load', 'speed', 'optimization']
  },
  {
    id: 'f6',
    category: 'Frontend & UI',
    taskName: 'Accessible keyboard navigation (WCAG 2.1 AA) overhaul',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Focus rings, aria-labels and trap-focus verified across all dialogs',
    plannedDetails: 'Audit screen reader compatibility and keyboard shortcuts for quick entry',
    keywords: ['accessibility', 'wcag', 'a11y', 'keyboard', 'aria', 'focus']
  },
  {
    id: 'f7',
    category: 'Frontend & UI',
    taskName: 'Real-time toast notifications & status update badges',
    priority: 'Low',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 2.5,
    timeSpent: 2,
    outputDeliverable: 'Polished toast notification provider for action feedback and alerts',
    plannedDetails: 'Add animated toasts on report save, submit, reject, and approve',
    keywords: ['toast', 'notification', 'feedback', 'ui', 'alerts', 'badges']
  },

  // DevOps & Cloud
  {
    id: 'd1',
    category: 'DevOps & Cloud',
    taskName: 'Configure CI/CD automated test pipeline in GitHub Actions',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: 'Automated test workflows passing on push and pull requests',
    plannedDetails: 'Setup multi-stage testing workflow with isolated MongoDB test environments',
    keywords: ['ci/cd', 'github actions', 'pipeline', 'devops', 'automation', 'tests']
  },
  {
    id: 'd2',
    category: 'DevOps & Cloud',
    taskName: 'Docker multi-container setup with Docker Compose',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4.5,
    outputDeliverable: 'Dockerized client, server and mongo services running seamlessly',
    plannedDetails: 'Package frontend in Nginx and backend in Alpine Node with network bridge',
    keywords: ['docker', 'compose', 'containers', 'nginx', 'deployment']
  },
  {
    id: 'd3',
    category: 'DevOps & Cloud',
    taskName: 'Cloud deployment configuration & environment security auditing',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 5,
    outputDeliverable: 'Production build deployed with HTTPS and CORS verification',
    plannedDetails: 'Configure production environment variables and verify TLS endpoints',
    keywords: ['cloud', 'deploy', 'security', 'cors', 'https', 'ssl', 'production']
  },
  {
    id: 'd4',
    category: 'DevOps & Cloud',
    taskName: 'Prometheus metrics & Grafana monitoring dashboards',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 5,
    outputDeliverable: 'Real-time CPU, RAM, HTTP latency and status code monitors configured',
    plannedDetails: 'Expose Prometheus metrics endpoint in Express backend and configure alerts',
    keywords: ['monitoring', 'grafana', 'prometheus', 'observability', 'metrics', 'alerts']
  },
  {
    id: 'd5',
    category: 'DevOps & Cloud',
    taskName: 'Automated daily database backup & S3 replication',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Cron-triggered mongodump script encrypting and shipping archives to S3',
    plannedDetails: 'Implement automated snapshot backups with 30-day retention policies',
    keywords: ['backup', 'database', 's3', 'disaster recovery', 'cron', 'mongodb']
  },

  // QA & Testing
  {
    id: 'q1',
    category: 'QA & Testing',
    taskName: 'Execute automated regression test suite & role boundary verification',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: '19/19 Jest test suites passing with zero broken handles',
    plannedDetails: 'Write automated integration tests for submission correction cycles and draft privacy',
    keywords: ['qa', 'jest', 'regression', 'testing', 'roles', 'permissions', 'integration']
  },
  {
    id: 'q2',
    category: 'QA & Testing',
    taskName: 'Cross-browser compatibility testing & accessibility audit',
    priority: 'Low',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 2.5,
    outputDeliverable: 'Verified flawless styling in Chrome, Edge, Firefox and Safari',
    plannedDetails: 'Audit keyboard tab navigation, contrast tokens and screen reader landmarks',
    keywords: ['cross-browser', 'qa', 'testing', 'safari', 'chrome', 'firefox', 'edge']
  },
  {
    id: 'q3',
    category: 'QA & Testing',
    taskName: 'End-to-End user journey tests with Cypress / Playwright',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 6,
    timeSpent: 6,
    outputDeliverable: 'Automated E2E tests for registration, report draft, review and approval flow',
    plannedDetails: 'Author resilient test selectors and headless execution in CI pipeline',
    keywords: ['e2e', 'cypress', 'playwright', 'testing', 'end-to-end', 'qa']
  },
  {
    id: 'q4',
    category: 'QA & Testing',
    taskName: 'API load testing & concurrent user benchmarking with k6',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 3.5,
    outputDeliverable: 'Benchmarked 250 req/sec sustained with sub-100ms p95 response time',
    plannedDetails: 'Stress test report submission endpoints under peak submission periods',
    keywords: ['k6', 'load testing', 'performance', 'benchmark', 'stress test', 'qa']
  },

  // Architecture & Docs
  {
    id: 'm1',
    category: 'Architecture & Docs',
    taskName: 'Technical documentation & API schema specification updates',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'README.md and API endpoint specifications fully documented',
    plannedDetails: 'Update ER diagrams and setup guides reflecting recent database schema changes',
    keywords: ['docs', 'architecture', 'openapi', 'swagger', 'readme', 'api docs']
  },
  {
    id: 'm2',
    category: 'Architecture & Docs',
    taskName: 'Code review, PR technical feedback & pair programming',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: 'Reviewed team pull requests and aligned on architectural patterns',
    plannedDetails: 'Conduct peer review sessions focusing on error boundaries and typing',
    keywords: ['code review', 'pr', 'pull request', 'architecture', 'standards', 'mentoring']
  },
  {
    id: 'm3',
    category: 'Architecture & Docs',
    taskName: 'Architecture Decision Record (ADR) for microservices & data model',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Published ADR #04 defining report versioning and snapshot persistence strategy',
    plannedDetails: 'Formalize data retention and version immutability architecture for audits',
    keywords: ['adr', 'architecture', 'design', 'decisions', 'documentation']
  },

  // Mobile & Apps
  {
    id: 'mb1',
    category: 'Mobile & Apps',
    taskName: 'Push notification service integration for weekly reminders',
    priority: 'High',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4.5,
    timeSpent: 4.5,
    outputDeliverable: 'FCM push notifications triggered for Friday report submission reminders',
    plannedDetails: 'Configure device token registration and scheduled trigger alerts',
    keywords: ['mobile', 'push', 'notifications', 'fcm', 'reminders', 'app']
  },
  {
    id: 'mb2',
    category: 'Mobile & Apps',
    taskName: 'Mobile touch gesture & bottom sheet drawer optimization',
    priority: 'Low',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 3,
    timeSpent: 3,
    outputDeliverable: 'Smooth 60fps swipe-to-dismiss drawer on mobile viewports',
    plannedDetails: 'Enhance quick-add interactions on mobile devices without layout shifts',
    keywords: ['mobile', 'touch', 'gestures', 'drawer', 'responsive', 'ui']
  },

  // Data & Analytics
  {
    id: 'da1',
    category: 'Data & Analytics',
    taskName: 'Automated weekly PDF report export & download service',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 5,
    timeSpent: 5.5,
    outputDeliverable: 'One-click branded PDF export with charts and summary tables',
    plannedDetails: 'Implement serverless PDF generation template matching company formatting',
    keywords: ['pdf', 'export', 'analytics', 'report', 'download', 'generator']
  },
  {
    id: 'da2',
    category: 'Data & Analytics',
    taskName: 'Weekly team velocity & completion rate data aggregation',
    priority: 'Medium',
    plannedPercentage: 100,
    actualPercentage: 100,
    status: 'Done',
    plannedTime: 4,
    timeSpent: 4,
    outputDeliverable: 'Aggregated analytics endpoint calculating on-time submission percentages',
    plannedDetails: 'Create MongoDB aggregation pipeline calculating department level velocity',
    keywords: ['analytics', 'metrics', 'velocity', 'aggregation', 'pipeline', 'reporting']
  }
];
